version: '3.9'
services:
  gameshub:
    image: 'docker-spring-boot-mysql:latest'
    build:
      context: .
    container_name: app
    depends_on:
      mysql-db:
          condition: service_healthy

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/springdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: qwerty12345

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: springdb
      MYSQL_ROOT_PASSWORD: qwerty12345
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
